stages:
  - validate
  - deploy

validate_procellariidae:
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'
    - if: '$CI_COMMIT_BRANCH == "test"'
  stage: validate
  script:
    - export YC_TOKEN=$(yc iam create-token)
    - export YC_CLOUD_ID=$(yc config get cloud-id)
    - export YC_FOLDER_ID=$(yc config get folder-id)
    - terraform init
    - terraform validate
  tags:
    - shell

deploy_procellariidae:
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'
    - if: '$CI_COMMIT_BRANCH == "test"'
  stage: validate
  script:
    - cp ./* /var/www/django-app/terraform
  tags:
    - shell