stages:
  - validate

validate_ubuntu:
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'
    - if: '$CI_COMMIT_BRANCH == "test"'
  stage: validate
  script:
    - export YC_TOKEN=$YC_TOKEN
    - export YC_CLOUD_ID=$YC_CLOUD_ID
    - export YC_FOLDER_ID=$YC_FOLDER_ID
    - ls -la
    - terraform init
    - terraform providers lock -net-mirror=https://terraform-mirror.yandexcloud.net -platform=linux_amd64 -platform=darwin_arm64 yandex-cloud/yandex
    - terraform validate
  tags:
    - shell